# Generated by Django 2.1.3 on 2020-05-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0002_brmuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brmuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='BRMuser',
        ),
    ]
